app = "tdf-hq"
image = "diegueins680/tdf-hq:latest"

[env]
  APP_PORT = "8080"
  ALLOW_ORIGINS = "https://tdf-app.pages.dev"
  ALLOW_ALL_ORIGINS = "true"
  VITE_PAYPAL_CLIENT_ID = "AfPPuaIkpj5aWoweUi1hL7s94NUo9fZdsN8e6P7v0zftuWAuWJvdNm6aHK_fboeSnZetnTLnnoBesxQ2"
  VITE_LIVE_SESSIONS_PUBLIC_TOKEN = "f96db9e5-8b43-4923-85d6-c1cc9bb2cb7f"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
